
# Site settings
title: "Anna Jacobsen"
header-img: "img/home-bg.jpg"
email: "anna@getdrip.com"
copyright_name: "Anna Jacobsen"
description: "Anna Jacobsen"
baseurl: "annajacobsen.co"
url: "http://annajacobsen.co"
twitter_username: "annagjacobsen"
github_username: "annaj"
facebook_username: "annajacobsen"
email_username: "anna@getdrip.com"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

-theme: startbootstrap-clean-blog-jekyll