
# Site settings
title: "Anna Jacobsen"
header-img: "img/anna-jacobsen-microconf-2018.png"
email: "annaj@hey.com"
copyright_name: "Anna Jacobsen"
description: "Anna Jacobsen"
baseurl: "annajacobsen.co"
url: "https://annajacobsen.co"
twitter_username: "annagjacobsen"
github_username: 
facebook_username: 
email_username: "annaj@hey.com"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-99309824-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

-theme: startbootstrap-clean-blog-jekyll

plugins:
  - jekyll-seo-tag

